# Generated by Django 2.1.4 on 2019-02-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20190213_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='scores',
            field=models.IntegerField(default=0),
        ),
    ]
