# Generated by Django 2.1.4 on 2019-02-13 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_review_scores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_name',
            new_name='restaurant_text',
        ),
    ]
