# Generated by Django 2.1.4 on 2019-02-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20190213_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='average_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='scores',
            field=models.IntegerField(default=0),
        ),
    ]
