# Generated by Django 2.1.4 on 2019-02-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_auto_20190218_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='scores',
            new_name='average_scores',
        ),
    ]
